
- name: start and enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted